# Site
name: "Occlusion"
title: "Occlusion"
description: "Programming blog with a focus on 3D rendering."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: ''
# disqus: ''
# mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  kemal:
    name: Kemal
    display_name: Kemal
    gravatar: ecd9b5d3527c4cfa71fcb0e0f4ebfe99
    email: kemalenver@gmail.com
    web: https://www.occlusion.io
    twitter: https://twitter.com/kemalenver
    description: "Software engineer from the UK.  Specialising in mobile development. Conservator of software. Passi interest in 3D rendering."
  
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
